// Code generated by internal/bridge/codegen. DO NOT EDIT.

export interface Empty {}

export interface SampleParams {
  foo: string;
  bar: number;
}

export interface SampleResult {
  ok: boolean;
}

export interface RpcMethods {
  "sample.doThing": { params: SampleParams; result: SampleResult };
}

export type RpcMethod = keyof RpcMethods;
export type RpcParams<M extends RpcMethod> = RpcMethods[M]["params"];
export type RpcResult<M extends RpcMethod> = RpcMethods[M]["result"];

export type EventTopic =
  | "sample.event";
