// Code generated by internal/bridge/codegen. DO NOT EDIT.

export interface AboutSettings {
  version: string;
  gitRev: string;
  buildDate: string;
}

export interface Conditions {
  processes?: string[];
  domains?: DomainMatcher[];
  ip_cidrs?: string[];
  geo?: string[];
  ports?: PortSpec[];
  protocols?: string[];
}

export interface DNSSettings {
  mode: string;
  servers: string[];
}

export interface DebugSettings {
  logLevel: string;
}

export interface DomainMatcher {
  kind: string;
  value: string;
}

export interface Empty {}

export interface GeneralSettings {
  language: string;
  autostart: boolean;
  startMinimized: boolean;
}

export interface Group {
  id: string;
  name: string;
  locked?: boolean;
  enabled: boolean;
  rules: Rule[];
}

export interface GroupView {
  id: string;
  name: string;
  locked: boolean;
  enabled: boolean;
  rules: RuleView[];
}

export interface HelperStatusResult {
  state: string;
}

export interface KillSwitchSettings {
  enabled: boolean;
  alwaysOn: boolean;
}

export interface Model {
  groups: Group[];
  default_action: string;
}

export interface NetworkSettings {
  defaultMode: string;
  tunCidr: string;
  tunMtu: number;
  tunName: string;
  socksPort: number;
  httpPort: number;
  allowLan: boolean;
  ipv6Mode: string;
  dns: DNSSettings;
}

export interface NotificationSettings {
  onConnected: boolean;
  onDisconnected: boolean;
  quotaLow: boolean;
  onSubSynced: boolean;
  sound: boolean;
}

export interface OnboardingStateResult {
  onboarded: boolean;
}

export interface PingResult {
  pong: number;
  version: string;
}

export interface PortSpec {
  single?: number;
  from?: number;
  to?: number;
}

export interface Rule {
  id: string;
  name: string;
  enabled: boolean;
  action: string;
  conditions: Conditions;
}

export interface RuleView {
  id: string;
  name: string;
  enabled: boolean;
  action: string;
  conditions: Conditions;
}

export interface RulesGroupAddParams {
  name: string;
}

export interface RulesGroupAddResult {
  id: string;
}

export interface RulesGroupEditParams {
  id: string;
  name: string;
  enabled: boolean;
}

export interface RulesGroupRemoveParams {
  id: string;
}

export interface RulesReplaceAllParams {
  model: Model;
}

export interface RulesRuleAddParams {
  groupId: string;
  rule: Rule;
}

export interface RulesRuleAddResult {
  id: string;
}

export interface RulesRuleEditParams {
  rule: Rule;
}

export interface RulesRuleMoveParams {
  id: string;
  toGroupId: string;
}

export interface RulesRuleRemoveParams {
  id: string;
}

export interface RulesRuleToggleParams {
  id: string;
}

export interface RulesView {
  defaultAction: string;
  groups: GroupView[];
}

export interface RunConnectParams {
  serverId: string;
  mode: string;
}

export interface RunReconnectParams {
  serverId: string;
  mode: string;
}

export interface RunSwitchModeParams {
  mode: string;
}

export interface SecuritySettings {
  method: string;
  available: boolean;
  warning?: string;
}

export interface ServerView {
  id: string;
  name: string;
  country: string;
  address: string;
  transport: string;
  security: string;
  latencyMs: number;
  origin: string;
  favorite: boolean;
  tags?: string[];
  uri: string;
}

export interface ServersAddParams {
  uri: string;
  name: string;
}

export interface ServersEditParams {
  id: string;
  uri: string;
  name: string;
}

export interface ServersEditResult {
  view: ServerView;
  vlessChanged: boolean;
}

export interface ServersRemoveParams {
  id: string;
}

export interface ServersTestLatencyParams {
  id: string;
}

export interface ServersToggleFavoriteParams {
  id: string;
}

export interface SettingsUpdateParams {
  section: string;
  patch: Record<string, unknown>;
}

export interface SettingsView {
  general: GeneralSettings;
  network: NetworkSettings;
  killSwitch: KillSwitchSettings;
  subscriptions: SubscriptionSettings;
  notifications: NotificationSettings;
  debug: DebugSettings;
  about: AboutSettings;
  security: SecuritySettings;
}

export interface Snapshot {
  status: string;
  currentServer?: ServerView | null;
  mode: string;
  speeds: SpeedSample;
  helperState: string;
  servers: ServerView[];
  subs: SubView[];
  settings: SettingsView;
  onboarded: boolean;
  version: string;
}

export interface SpeedSample {
  upBps: number;
  downBps: number;
  at: string;
}

export interface SubView {
  id: string;
  name: string;
  url: string;
  updateInterval: number;
  lastSyncAt: string;
  lastSyncStatus: string;
  lastSyncMessage?: string;
  serverCount: number;
  upload?: number;
  download?: number;
  total?: number;
  expire?: string | null;
  userAgent?: string;
}

export interface SubsAddParams {
  url: string;
  name: string;
}

export interface SubsEditParams {
  id: string;
  url: string;
  name: string;
}

export interface SubsRemoveParams {
  id: string;
}

export interface SubsSyncOneParams {
  id: string;
}

export interface SubscriptionSettings {
  defaultUpdateInterval: number;
  userAgent: string;
  hwidEnabled: boolean;
  sendDeviceOS: boolean;
  sendOSVersion: boolean;
  sendDeviceModel: boolean;
}

export interface RpcMethods {
  "app.getPublicIP": { params: Empty; result: string };
  "app.getSnapshot": { params: Empty; result: Snapshot };
  "app.ping": { params: Empty; result: PingResult };
  "helper.install": { params: Empty; result: Empty };
  "helper.reinstall": { params: Empty; result: Empty };
  "helper.restart": { params: Empty; result: Empty };
  "helper.start": { params: Empty; result: Empty };
  "helper.status": { params: Empty; result: HelperStatusResult };
  "helper.stop": { params: Empty; result: Empty };
  "onboarding.complete": { params: Empty; result: Empty };
  "onboarding.getState": { params: Empty; result: OnboardingStateResult };
  "onboarding.skip": { params: Empty; result: Empty };
  "rules.groupAdd": { params: RulesGroupAddParams; result: RulesGroupAddResult };
  "rules.groupEdit": { params: RulesGroupEditParams; result: Empty };
  "rules.groupRemove": { params: RulesGroupRemoveParams; result: Empty };
  "rules.list": { params: Empty; result: RulesView };
  "rules.replaceAll": { params: RulesReplaceAllParams; result: Empty };
  "rules.ruleAdd": { params: RulesRuleAddParams; result: RulesRuleAddResult };
  "rules.ruleEdit": { params: RulesRuleEditParams; result: Empty };
  "rules.ruleMove": { params: RulesRuleMoveParams; result: Empty };
  "rules.ruleRemove": { params: RulesRuleRemoveParams; result: Empty };
  "rules.ruleToggle": { params: RulesRuleToggleParams; result: Empty };
  "run.connect": { params: RunConnectParams; result: Empty };
  "run.disconnect": { params: Empty; result: Empty };
  "run.reconnect": { params: RunReconnectParams; result: Empty };
  "run.switchMode": { params: RunSwitchModeParams; result: Empty };
  "servers.add": { params: ServersAddParams; result: ServerView };
  "servers.edit": { params: ServersEditParams; result: ServersEditResult };
  "servers.list": { params: Empty; result: ServerView[] };
  "servers.remove": { params: ServersRemoveParams; result: Empty };
  "servers.testLatency": { params: ServersTestLatencyParams; result: Empty };
  "servers.toggleFavorite": { params: ServersToggleFavoriteParams; result: Empty };
  "settings.get": { params: Empty; result: SettingsView };
  "settings.update": { params: SettingsUpdateParams; result: SettingsView };
  "subs.add": { params: SubsAddParams; result: SubView };
  "subs.edit": { params: SubsEditParams; result: SubView };
  "subs.list": { params: Empty; result: SubView[] };
  "subs.remove": { params: SubsRemoveParams; result: Empty };
  "subs.syncAll": { params: Empty; result: Empty };
  "subs.syncOne": { params: SubsSyncOneParams; result: SubView };
}

export type RpcMethod = keyof RpcMethods;
export type RpcParams<M extends RpcMethod> = RpcMethods[M]["params"];
export type RpcResult<M extends RpcMethod> = RpcMethods[M]["result"];

export type EventTopic =
  | "bridge.state"
  | "chain.error"
  | "helper.state"
  | "probe.result"
  | "rules.changed"
  | "servers.changed"
  | "sub.synced"
  | "vpn.speed"
  | "vpn.status";
